### ISSUE TITLE
Message "zhegvdx_gpu error: cusolverDnZpotrf failed!" on Kepler architecture

### ISSUE THREAD

**Issue by fspiga** [RSE-Cambridge/qe-gpu#13]
## Version of QE-GPU

git hash 767e2cd55095ef17f666c9328dee6d9ebd4b44af

### Expected behavior/result

Computation progress correctly

### Actual behavior/result

A crash occurs inside `cdiaghg`, not sure when used the first time or also in other occasion (need further investigation)

```
     negative rho (up, down):  3.043E+00 0.000E+00
     Starting wfc are 1008 randomized atomic wfcs
 zhegvdx_gpu error: cusolverDnZpotrf failed!

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine cdiaghg (1):
     incorrect call to ZHEGV*
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

     stopping ...
--------------------------------------------------------------------------
```

### Steps to reproduce behavior/result

Use `install/make.inc_x86-64`, set `GPU_ARCH=35` in make.inc. The problem exists using both PGI 17.4 (Community edition) and PGI 17.5 (Professional Edition), using both SiO2 and AUSURF112 test-cases. MKL 11.3.3.210 has been used but I do not think it is the issue here (I always use this version).

**Comment by maxcuda** [comment]
ZGEMM3M is supported only on cc5.0 and up.

A workaround for now is to change it back to the regular ZGEMM.

In PW/src, you can execute this command:

grep -Rl "cublasZgemm3m" *.F90 *.f90   |xargs sed -i 's/cublasZgemm3m/cublasZgemm3m/'

**Comment by fspiga** [comment]
I created a branch called `bugfix/13`, I'll commit changes and test them there first before squash into devel-gpu
