### ISSUE TITLE
Fix CPU compilation

### ISSUE THREAD

**Issue by fspiga** [RSE-Cambridge/qe-gpu#2]
Currently the code does not compile for CPU-only. Fix needed.

**Comment by maxcuda** [comment]
The code compiles with the right modifications to make.inc:

.F90.o:
        $(MPIF90) $(F90FLAGS) -c $< -o $(*)_cpu.o ; \
        ld -r $(*)_cpu.o -o $(*).o ; \
        rm $(*)_cpu.o

DFLAGS         =  -D__OPENMP -D__PGI -D__FFTW -D__MPI
IFLAGS         = -I$(TOPDIR)/include -I../include/
F90FLAGS       = -O3 -Mpreprocess -Mcache_align -mp $(FDFLAGS) $(IFLAGS) $(MODFLAGS)

It is however segfaulting in the diagonalization.

**Comment by maxcuda** [comment]
Fixed the segfault. With the proper make.inc the code will compile and run in CPU-only mode.
Leaving the issue open until fspiga fixed the configure to generate the correct make.inc

**Comment by fspiga** [comment]
When "fix-build-process" merges into devel-gpu the fix will be active
