### ISSUE TITLE
"USE_GPU_MPI" as default

### ISSUE THREAD

**Issue by fspiga** [RSE-Cambridge/qe-gpu#20]
Open MPI shipped with PGI is compiled with CUDA support, Spectrum MPI for POWER is CUDA-aware. Is there any reason why `USE_GPU_MPI` should not be set as default?

**Comment by maxcuda** [comment]
OpenMPI with PGI is not compiled with CUDA support by default. I am also not sure it will give a benefit in generic systems. I would leave it as an optional flag.

**Comment by fspiga** [comment]
mmm my Open MPI shipped with PGI Community Edition is CUDA enabled (unless my interpretation of `ompi_info` is wrong)

```
[fspiga@dev-box ~]$ ompi_info --all | grep cuda
                 MCA mpi: informational "mpi_built_with_cuda_support" (current value: "true", data source: default, level: 4 tuner/basic, type: bool)
                 MCA mpi: parameter "mpi_cuda_support" (current value: "true", data source: default, level: 4 tuner/basic, type: bool)
                 MCA btl: parameter "btl_smcuda_use_cuda_ipc" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                 MCA btl: parameter "btl_smcuda_use_cuda_ipc_same_gpu" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
```

**Comment by romerojosh** [comment]
I think if you just go with all the default responses from running the install script for PGI, CUDA-aware will be enabled (I'll check when I get in today). If we can verify that the CUDA-aware MPI path provides better performance on all our various systems, I don't necessarily see an issue enabling it by default, since it's good to put our best foot forward.
On the other hand, for users new to GPUs, if they run with a non-CUDA aware MPI (perhaps they choose to not use the MPI packaged with PGI), the errors generated in this case are not at all obvious, since the code will simply segfault on MPI calls. Could lead to some confusion.

**Comment by romerojosh** [comment]
PGI doesn't enable CUDA-aware features in the packaged OpenMPI by default. From the install:

************************************************************************
MPI
************************************************************************
This release contains version 1.10.2 of the Open MPI library.

Press enter to continue...

Do you want to install Open MPI onto your system? (y/n) y
Do you want to enable NVIDIA GPU support in Open MPI? (y/n) 

Installing Open MPI 1.10.2 components into /home/joshr/pgi-scratch ... Done


Installing ScaLAPACK 2.0.2 components into /home/joshr/pgi-scratch ... Done

 
Note: Open MPI's support for NVIDIA GPUs can be re-enabled at any time.
Refer to the PGI Installation Guide at www.pgroup.com for details.
 
Press enter to continue...

Just pressing enter on the NVIDIA GPU support question yields this which seems to imply that the feature is disabled by default.

Probably should leave the flag optional but in the README strongly suggest trying it out.

**Comment by maxcuda** [comment]
We can add the flag as a comment in the make.inc but It should be an opt-in.

On my system is 
ompi_info --all | grep cuda
                 MCA mpi: informational "mpi_built_with_cuda_support" (current value: "true", data source: default, level: 4 tuner/basic, type: bool)
                 MCA mpi: parameter "mpi_cuda_support" (current value: "false", data source: environment, level: 4 tuner/basic, type: bool)
                 MCA btl: parameter "btl_self_cuda_eager_limit" (current value: "0", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_self_cuda_rdma_limit" (current value: "18446744073709551615", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_smcuda_free_list_num" (current value: "8", data source: default, level: 5 tuner/detail, type: int)
                 MCA btl: parameter "btl_smcuda_free_list_max" (current value: "-1", data source: default, level: 5 tuner/detail, type: int)
                 MCA btl: parameter "btl_smcuda_free_list_inc" (current value: "64", data source: default, level: 5 tuner/detail, type: int)
                 MCA btl: parameter "btl_smcuda_max_procs" (current value: "-1", data source: default, level: 5 tuner/detail, type: int)
                 MCA btl: parameter "btl_smcuda_fifo_size" (current value: "4096", data source: default, level: 4 tuner/basic, type: unsigned)
                 MCA btl: parameter "btl_smcuda_num_fifos" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                 MCA btl: parameter "btl_smcuda_fifo_lazy_free" (current value: "120", data source: default, level: 5 tuner/detail, type: unsigned)
                 MCA btl: parameter "btl_smcuda_sm_extra_procs" (current value: "0", data source: default, level: 9 dev/all, type: int)
                 MCA btl: parameter "btl_smcuda_use_cuda_ipc" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                 MCA btl: parameter "btl_smcuda_use_cuda_ipc_same_gpu" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                 MCA btl: parameter "btl_smcuda_cuda_ipc_verbose" (current value: "0", data source: default, level: 4 tuner/basic, type: int)
                 MCA btl: parameter "btl_smcuda_exclusivity" (current value: "0", data source: default, level: 7 dev/basic, type: unsigned)
                 MCA btl: parameter "btl_smcuda_flags" (current value: "1", data source: default, level: 5 tuner/detail, type: unsigned)
                 MCA btl: parameter "btl_smcuda_rndv_eager_limit" (current value: "4096", data source: default, level: 4 tuner/basic, type: size_t)
                 MCA btl: parameter "btl_smcuda_eager_limit" (current value: "4096", data source: default, level: 4 tuner/basic, type: size_t)
                 MCA btl: parameter "btl_smcuda_cuda_eager_limit" (current value: "18446744073709551615", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_smcuda_cuda_rdma_limit" (current value: "18446744073709551615", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_smcuda_max_send_size" (current value: "131072", data source: default, level: 4 tuner/basic, type: size_t)
                 MCA btl: parameter "btl_sm_cuda_eager_limit" (current value: "0", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_sm_cuda_rdma_limit" (current value: "18446744073709551615", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_tcp_cuda_eager_limit" (current value: "0", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_tcp_cuda_rdma_limit" (current value: "18446744073709551615", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_openib_cuda_async_send" (current value: "true", data source: default, level: 9 dev/all, type: bool)
                 MCA btl: parameter "btl_openib_cuda_async_recv" (current value: "true", data source: default, level: 9 dev/all, type: bool)
                 MCA btl: informational "btl_openib_have_cuda_gdr" (current value: "true", data source: default, level: 5 tuner/detail, type: bool)
                 MCA btl: parameter "btl_openib_want_cuda_gdr" (current value: "false", data source: default, level: 9 dev/all, type: bool)
                 MCA btl: parameter "btl_openib_cuda_eager_limit" (current value: "0", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_openib_cuda_rdma_limit" (current value: "18446744073709551615", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_vader_cuda_eager_limit" (current value: "0", data source: default, level: 5 tuner/detail, type: size_t)
                 MCA btl: parameter "btl_vader_cuda_rdma_limit" (current value: "18446744073709551615", data source: default, level: 5 tuner/detail, type: size_t)
                MCA coll: parameter "coll_cuda_priority" (current value: "78", data source: default, level: 6 tuner/all, type: int)
                          Priority of the cuda coll component; only relevant if barrier_before or barrier_after is > 0
                MCA coll: parameter "coll_cuda_disable_cuda_coll" (current value: "0", data source: default, level: 2 user/detail, type: int)

**Comment by fspiga** [comment]
Let collect all information about pre-processor macros and their effect here: https://github.com/RSE-Cambridge/qe-gpu/blob/devel-gpu/install/README.DFLAGS
