### ISSUE TITLE
Enabling openmp on Power will cause an internal compiler error for two files

### ISSUE THREAD

**Issue by maxcuda** [RSE-Cambridge/qe-gpu#3]
## Version of QE-GPU

Current version

### Expected behavior/result

pgf90 should be able to compile read_file_new.f90 and pw_restart.f90 with the -mp flag 

The workaround at the moment is to remove the -mp flag for these two files.

The makefile needs to be modified.

**Comment by fspiga** [comment]
Using PGI Community Edition 17.4 on POWER I can reproduce the problem with "pw_restart.f90" but not with "read_file_new.f90". I set a different compilation path for both if the variable `F90FLAGS_WORKAROUND` is defined in the make.inc. Small changes in the `PW/src/Makefile` protected by a conditional. 

Fix present in PR #4, ready for merge.
