### ISSUE TITLE
Invalid mpicc command on Cray systems

### ISSUE THREAD

**Issue by bonfus** [RSE-Cambridge/qe-gpu#30]
The following line breaks the compilation on Piz Daint (Cray system) where `cc` is used instead.

https://github.com/RSE-Cambridge/qe-gpu/blob/b1ae242db647749fdf02ce61bb16aa2ea2b33fde/FFTXlib/Makefile#L44

**Comment by fspiga** [comment]
CRAY environment so annoying sometimes...

I'll add a `MPICC` field in the `make.inc` templates.
