### ISSUE TITLE
Total energy different when using OpenMP: compiler/lib problem or bug?

### ISSUE THREAD

**Issue by bonfus** [RSE-Cambridge/qe-gpu#31]
This bug was originally reported by Ifeanyi John Onuorah.

### Version of QE-GPU

     Program PWSCF v.6.1 (gpu tag v0.3) starts on 29Sep2017 at 21: 2:36 

commit 1f53a7929a7b18443449b3e65d1c6bc0220dfc36 (Reverting was not done).

### Expected behavior/result

The same result should be obtained when using `OMP_NUM_THREADS=1` or `OMP_NUM_THREADS>1`

### Actual behavior/result

Total energies are very different:

    fe.scf.in_CSCS_GPU-no_omp.out:!    total energy              =   -5269.31116749 Ry
    fe.scf.in_CSCS_GPU.out:!    total energy              =   -4753.26793496 Ry

This is mainly due to the `one-center paw contrib` contribution.

### Steps to reproduce behavior/result

Use this input file: [omp_bug.tar.gz](https://github.com/RSE-Cambridge/qe-gpu/files/1347534/omp_bug.tar.gz)

* architecture: CRAY XC50 (Piz Daint)
* type of GPU you are using:  NVIDIA® Tesla® P100 16GB
* version and flavor of MPI: pgi module installed on pizdaint
* PGI compiler: 17.4
* the full ``DFLAGS`` line:` -DUSE_CUDA -D__FFTW -D__MPI -D__MKL`
* how you run the code: 2 nodes, 2 MPI processes, 1 or 12 threads.

**Comment by fspiga** [comment]
Which Intel MKL library are you using? Have you tried a different MKL library?

It seems you already know where the potential bug is located. Have you tried to disable that portion of the code and re-run?

If you are able find quickly the solution, please fork and then open a PR!

**Comment by romerojosh** [comment]
Reproduced and figured out the problem. The `DFLAGS` line requires the addition of the following: `-D__OPENMP` to enable some threaded logic that is used for the one-center paw computation (in `paw_onecenter.f90`). This wasn't an issue in some of the cases we were using for development which is why it was removed, but it is clearly required.

This flag should be added back to all the template make.inc files before closing the issue.

**Comment by romerojosh** [comment]
@bonfus: Do you know if the executable used on Piz Daint by Ifeanyi was compiled before or after the Piz Daint system update? This is for a separate issue we are having with the current environment which is causing issues with the code.

**Comment by romerojosh** [comment]
@bonfus: Disregard my previous inquiry. We have figured out the issue and will be pushing a fix.

**Comment by romerojosh** [comment]
Flag was only missing from Piz Daint template make.inc. Fixed with commit 646ecc4cbff6df5079eae07cc046582a6d41787f.
