### ISSUE TITLE
Verify and test restart functionality

### ISSUE THREAD

**Issue by romerojosh** [RSE-Cambridge/qe-gpu#6]
Up to this point, GPU code has only been tested starting from scratch. We need to verify that device data is being allocated/initialized properly when restarted.

**Comment by fspiga** [comment]
I just tested restart using AUSURF112 and SiO2, it works if `disk_io` is default (meaning) or not present. If set to `disk_io = 'none'` (reduced I/O, all loaded in memory) then the code crashed due to missing file(s).

I/O is currently a **mess** and it is undergoing big transformation. We should re-evaluate I/O impact once the CPU code is align to v6.1 and the next release due end of summer. It is something QE-GPU inherits from standard QE, it should not impact the GPU developments.

**Comment by maxcuda** [comment]
After reading the data from file, the proper arrays should be copied to GPU memory. I think this is missing at the moment.

**Comment by fspiga** [comment]
I am waiting tests to finish, I'll upload the outputs somewhere for comparison.

**Comment by fspiga** [comment]
Various outputs here: https://goo.gl/ADwjgv

Input files:
- `ausurf_k.in` = input case with full SCF and forces calculation 
- `ausurf_k_p1.in` = input case that triggers safe stop after 2 SCF iterations
- `ausurf_k_p2.in` = input case that resume from p1 safely and complete the SCF and forces calculation

Full outputs:
- `out.full.CPU` = running `ausurf_k.in` using CPU (8 MPI, 3 OMP)
- `out.full.GPU` = running `ausurf_k.in` using GPU (8 MPI, 8 NVIDIA K80)

Outputs with stop & restart:
- `out.p1.CPU` = running `ausurf_k_p1.in` using CPU (8 MPI, 3 OMP)
- `out.p1.GPU` = running `ausurf_k_p1.in` using GPU (8 MPI, 8 NVIDIA K80)
- `out.p2.CPU` = running `ausurf_k_p2.in` using CPU (8 MPI, 3 OMP)
- `out.p2.GPU` = running `ausurf_k_p2.in` using GPU (8 MPI, 8 NVIDIA K80)

By comparing `out.p1.CPU` versus `out.p1.GPU`  and `out.p2.CPU` versus `out.p2.GPU` you can see the energies match.

The forces calculation concerns me, numbers do not match ...

**Comment by romerojosh** [comment]
These CPU reference numbers are using the QE-GPU code right? Is it possible to get a reference output using the baseline QE code. I'd be interested to see the force values after a full run on the CPU there.

**Comment by fspiga** [comment]
I can repeat again all tests using the v6.1 released in March and run the just aligned QE-GPU. I'll upload when ready.
